/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kerja;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;


public class KerjaNet extends javax.swing.JFrame {

  


    public KerjaNet() {
        initComponents();
   
    }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        Login_Panel = new javax.swing.JPanel();
        Sign_In = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1_Username = new javax.swing.JLabel();
        jTextField_UserName_SignIn = new javax.swing.JTextField();
        javax.swing.JLabel jLabel1_Username1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton_SignIn = new javax.swing.JButton();
        jButton_PindahKeSignUp = new javax.swing.JButton();
        jPasswordField_PasswordSignIn = new javax.swing.JPasswordField();
        Sign_Up = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton_SignUp = new javax.swing.JButton();
        jButton_PindahKeSignIn = new javax.swing.JButton();
        javax.swing.JLabel jLabel1_Username2 = new javax.swing.JLabel();
        jTextField_UserName_SignUp = new javax.swing.JTextField();
        javax.swing.JLabel jLabel1_Username3 = new javax.swing.JLabel();
        jPasswordField_PasswordSignUp = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(536, 357));

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(940, 540));

        Login_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Login_Panel.setLayout(new java.awt.CardLayout());

        jLabel1_Username.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1_Username.setText("User Name");

        jTextField_UserName_SignIn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel1_Username1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1_Username1.setText("Password");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-interface.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jButton_SignIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_SignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/enter.png"))); // NOI18N
        jButton_SignIn.setText("Sign In");
        jButton_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SignInActionPerformed(evt);
            }
        });

        jButton_PindahKeSignUp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_PindahKeSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/upload.png"))); // NOI18N
        jButton_PindahKeSignUp.setText("Create Account");
        jButton_PindahKeSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PindahKeSignUpActionPerformed(evt);
            }
        });

        jPasswordField_PasswordSignIn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout Sign_InLayout = new javax.swing.GroupLayout(Sign_In);
        Sign_In.setLayout(Sign_InLayout);
        Sign_InLayout.setHorizontalGroup(
            Sign_InLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sign_InLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Sign_InLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sign_InLayout.createSequentialGroup()
                        .addGroup(Sign_InLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1_Username)
                            .addComponent(jTextField_UserName_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Sign_InLayout.createSequentialGroup()
                        .addComponent(jButton_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_PindahKeSignUp))
                    .addGroup(Sign_InLayout.createSequentialGroup()
                        .addGroup(Sign_InLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1_Username1)
                            .addComponent(jPasswordField_PasswordSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Sign_InLayout.setVerticalGroup(
            Sign_InLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sign_InLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Sign_InLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(Sign_InLayout.createSequentialGroup()
                        .addComponent(jLabel1_Username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_UserName_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jLabel1_Username1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_PasswordSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(Sign_InLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_PindahKeSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        Login_Panel.add(Sign_In, "card2");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-user.png"))); // NOI18N

        jButton_SignUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_SignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        jButton_SignUp.setText("Sign Up");
        jButton_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SignUpActionPerformed(evt);
            }
        });

        jButton_PindahKeSignIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_PindahKeSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/preview.png"))); // NOI18N
        jButton_PindahKeSignIn.setText("Back To Sign In");
        jButton_PindahKeSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PindahKeSignInActionPerformed(evt);
            }
        });

        jLabel1_Username2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1_Username2.setText("User Name");

        jTextField_UserName_SignUp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel1_Username3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1_Username3.setText("Password");

        jPasswordField_PasswordSignUp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout Sign_UpLayout = new javax.swing.GroupLayout(Sign_Up);
        Sign_Up.setLayout(Sign_UpLayout);
        Sign_UpLayout.setHorizontalGroup(
            Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sign_UpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sign_UpLayout.createSequentialGroup()
                        .addComponent(jPasswordField_PasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Sign_UpLayout.createSequentialGroup()
                        .addGroup(Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1_Username2)
                            .addComponent(jTextField_UserName_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1_Username3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(Sign_UpLayout.createSequentialGroup()
                        .addComponent(jButton_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_PindahKeSignIn)))
                .addContainerGap())
        );
        Sign_UpLayout.setVerticalGroup(
            Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sign_UpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(Sign_UpLayout.createSequentialGroup()
                        .addComponent(jLabel1_Username2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_UserName_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1_Username3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_PasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_SignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton_PindahKeSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        Login_Panel.add(Sign_Up, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Login_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Login_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SignInActionPerformed
    String url = "jdbc:sqlserver://localhost:1433;databaseName=login_db;encrypt=true;trustServerCertificate=true;";
    String user = "sa"; 
    String password = "arkhan123"; 

    String inputUsername = jTextField_UserName_SignIn.getText();
    String inputPassword = jPasswordField_PasswordSignIn.getText();

    String sql = "SELECT * FROM users WHERE username = ? AND password = ?";

    try (Connection conn = DriverManager.getConnection(url, user, password);
         PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setString(1, inputUsername);
        stmt.setString(2, inputPassword);

        ResultSet login = stmt.executeQuery();

        if (login.next()) {
            JOptionPane.showMessageDialog(null, "Login berhasil!");
            Dashboard dashboard = new Dashboard();
            dashboard.setVisible(true);
            this.dispose();
        } else {
            jPasswordField_PasswordSignIn.setText("");
            JOptionPane.showMessageDialog(null, "Username atau password salah.");
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal login: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton_SignInActionPerformed

    private void jButton_PindahKeSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PindahKeSignUpActionPerformed
        Login_Panel.removeAll();
        Login_Panel.repaint();
        Login_Panel.revalidate();

        Login_Panel.add(Sign_Up);
        Login_Panel.repaint();
        Login_Panel.revalidate();
        jTextField_UserName_SignIn.setText("");
        jPasswordField_PasswordSignIn.setText("");
    }//GEN-LAST:event_jButton_PindahKeSignUpActionPerformed

    private void jButton_PindahKeSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PindahKeSignInActionPerformed
        Login_Panel.removeAll();
        Login_Panel.repaint();
        Login_Panel.revalidate();

        Login_Panel.add(Sign_In);
        Login_Panel.repaint();
        Login_Panel.revalidate();
        jTextField_UserName_SignUp.setText("");
        jPasswordField_PasswordSignUp.setText("");
    }//GEN-LAST:event_jButton_PindahKeSignInActionPerformed

    private void jButton_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SignUpActionPerformed
    String url = "jdbc:sqlserver://localhost\\LEINAVON:1433;databaseName=login_db;encrypt=true;trustServerCertificate=true;";
    String user = "sa"; 
    String password = "arkhan123";

    String username = jTextField_UserName_SignUp.getText();
    String passwordInput = jPasswordField_PasswordSignUp.getText();

    String sql = "INSERT INTO users (username, password) VALUES (?, ?)";

try (Connection conn = DriverManager.getConnection(url, user, password);
     PreparedStatement stmt = conn.prepareStatement(sql)) {

    stmt.setString(1, username);
    stmt.setString(2, passwordInput);
    stmt.executeUpdate();

    JOptionPane.showMessageDialog(null, "Sign up berhasil!");

} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Gagal sign up: " + e.getMessage());
}
    jTextField_UserName_SignUp.setText("");
    jPasswordField_PasswordSignUp.setText("");
    }//GEN-LAST:event_jButton_SignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KerjaNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KerjaNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KerjaNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KerjaNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        java.awt.EventQueue.invokeLater(() -> {
        new KerjaNet().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login_Panel;
    private javax.swing.JPanel Sign_In;
    private javax.swing.JPanel Sign_Up;
    private javax.swing.JButton jButton_PindahKeSignIn;
    private javax.swing.JButton jButton_PindahKeSignUp;
    private javax.swing.JButton jButton_SignIn;
    private javax.swing.JButton jButton_SignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField_PasswordSignIn;
    private javax.swing.JPasswordField jPasswordField_PasswordSignUp;
    private javax.swing.JTextField jTextField_UserName_SignIn;
    private javax.swing.JTextField jTextField_UserName_SignUp;
    // End of variables declaration//GEN-END:variables
}
